### ISSUE TITLE
Media/streaming icons on release pages bugged after latest update

### ISSUE THREAD

**Issue by Wyyvern** [jgchk/better-rym#123]
Hopefully an easy thing to fix, the media icons for streaming links are 'empty' even when links have been added, and the bandcamp embed doesn't seem to be loading (not sure if that specifically is an extension issue or new site issue). On loading the page you can see the spinny wheel thing, and you can still click to get to a retrieved page, they're just not showing as 'full' when a link has been submitted.

![image](https://user-images.githubusercontent.com/44896434/165381505-4574bed5-d69b-4cb3-b812-5af1efc8f75d.png)

Everything else seems to be working after the new site update, adding releases, cover art, and streaming links including bandcamp link conversion all works. ^^

**Comment by jgchk** [comment]
thanks for the report :^)

looks like rym is now dynamically loading stream links through a JS script which breaks our old scraping method

its actually a great change for better-rym though since they're passing in the links as JSON now (check out `data-links`)
![image](https://user-images.githubusercontent.com/21698192/165389469-d4f25990-01d2-46f1-9a97-cbff82317802.png)

should have a fix up very soon

**Comment by jgchk** [comment]
fixed in dd3a29c88a9a29cc5b3b636e283c68c4788bb91e

update submitted to chrome & firefox. should be coming to your browser in the next hour or so :D

**Comment by Wyyvern** [comment]
The update went through a few hours back, using it for a bit, it seems to be a bit patchy.

Sometimes the icons that should be 'full' appear as they should, sometimes they're still blank.
On some occasions I'm also getting infinite loading wheels, and instant fails with a red x on each icon.

https://rateyourmusic.com/release/album/darkspace/dark-space-i/ - they all work as intended here.
https://rateyourmusic.com/release/album/darkspace/dark-space-ii/ - fails instantly, red x's on each icon.
https://rateyourmusic.com/release/album/darkspace/dark-space-iii/ - infinite loading on each icon.
https://rateyourmusic.com/release/single/kardashev/compost-grave-song/ - I've added spotify + youtube links for this, icons are still 'empty'

Hopefully it's replicable on your end. Might be because it's a new update, maybe it'll rectify by itself by tomorrow but thought I'd let you know anyways.

**Comment by jgchk** [comment]
instant fails and infinite loading should be fixed in the latest update (had an issue with content script sandboxing, yuck)

the empty icons seems to be a bug on rym's end. i'm still not seeing them pop up even with betterrym disabled. seems like others are seeing the same issue as well https://rateyourmusic.com/discussion/rate-your-music/rym-april-2022-update/6/#post_8321100
